#!/usr/bin/env python
"""CSV converter for Zisa"""

import csv
import json
import os
import sys

from collections import namedtuple
from itertools import imap


def convert(input_file, output_dir):
    """Converts the CSV input_file to JSON per row."""

    print 'Converting %s to %s' % (input_file, output_dir)

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    with open(input_file) as csvfile:
        reader = csv.reader(csvfile)
        Row = namedtuple('Row', next(reader))
        for row in imap(Row._make, reader):
            doc = {
                "version": "1.0.0",
                "contributorId": row.contributorId,
                "action": row.action,
                "assets": [{
                    "uri": row.uri,
                    "metadata": {
                        "headline": row.headline,
                        "keywords": row.keywords.split(","),
                        "licenseType": row.licenseType,
                        "premiumLevel": int(row.premiumLevel)
                    },
                    "partnerAssetId": row.partnerAssetId,
                    "assetType": row.assetType,
                    "height": int(row.height),
                    "width": int(row.width)
                }]
            }

            out = open(
                os.path.join(output_dir, row.partnerAssetId + '.json'), 'w')

            print >> out, json.dumps(doc, indent=4)
            out.close()

    csvfile.close()


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print 'Usage:'
        print ' $ converter <some_csv_file.csv> /some/output/path'
        sys.exit(1)

    convert(sys.argv[1], sys.argv[2])
